services:
  meet:
    image: ghcr.io/kevinantoniowiyonolauw/meet:latest
    pull_policy: always
    container_name: meet
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/meet.db
    volumes:
      - meet-data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meet.rule=Host(`meet.kevinio.my.id`)"
      - "traefik.http.routers.meet.entrypoints=web"
      - "traefik.http.services.meet.loadbalancer.server.port=3000"

volumes:
  meet-data:

networks:
  proxy:
    external: true